defaults:
  run:
    working-directory: platform/web/

name: Deploy to Github Pages
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Setup wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Create necessary wasm files
        run: wasm-pack build --release --target web

      # pkg/ folder contains .gitignore so don't use it!
      - name: Move index.html and script.js into the generated repo pkg/ then copy pkg/ to public/
        run: |
          cp index.html pkg/
          cp script.js pkg/
          mkdir public
          cp pkg/* public
          rm -rf pkg/*
          cd public
          ls .

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: platform/web/public
          branch: gh-pages
